repos:
    - repo: https://github.com/ambv/black
      rev: 19.10b0
      hooks:
          - id: black
            language_version: python3
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.9
      hooks:
          - id: flake8
            exclude: ^build/*
            additional_dependencies:
                - flake8-builtins
                - flake8-comprehensions
                - flake8-docstrings
                - flake8-tuple
                - flake8-quotes
                - pep8-naming
                - pydocstyle<4.0.0
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.770
      hooks:
          - id: mypy
            exclude: ^((tests|bin)\/)?[\w-]+\.py$
            args: ["--disallow-untyped-defs", "--ignore-missing-imports"]
