name: publish-docs
on:
  push:
    branches: [master]
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.6.15

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Install Poetry
        run: pip install poetry==1.1.15

      - name: Cache Poetry virtualenv
        uses: actions/cache@v2
        id: poetry-cache
        with:
          path: ~/.cache/pypoetry
          key: poetry-3.6-${{ hashFiles('poetry.lock', 'pyproject.toml') }}
          restore-keys: poetry-3.6-

      - name: Install App and Dependencies
        run: poetry install

      - name: Build Docs
        run: poetry run build-docs

      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
